### 设置服务端口和Tomcat编码格式
server:
  port: 8188
  tomcat:
    uri-encoding: UTF-8

### 设置服务名称
spring:
  application:
    name: botong-zuul
  cloud:
    config:
      fail-fast: true
      discovery:
        enabled: true
        service-id: botong-config
      profile: dev
      label: master

##配置路由忽略服务和是否重试；并利配置链接超时时间
zuul:
  ignoredServices: '*'
  retryable: true
  host:
      connect-timeout-millis: 30000
      socket-timeout-millis: 60000
  routes:
    admin:
      path: /admin/**
      serviceId: botong-admin

##配置注册中心
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8181/eureka/
  instance:
    preferIpAddress: true

hystrix:
  threadpool:
    default:
      coreSize: 1000 ##并发执行的最大线程数，默认10
      maxQueueSize: 1000 ##BlockingQueue的最大队列数
      queueSizeRejectionThreshold: 500 ##即使maxQueueSize没有达到，达到queueSizeRejectionThreshold该值后，请求也会被拒绝
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 50000
          strategy: SEMAPHORE


gate:
  ignore:
    uri: /admin/api/adminUser/login