### 设置服务端口和Tomcat编码格式
server:
  port: 8000
  tomcat:
    uri-encoding: UTF-8

### 设置服务名称
spring:
  application:
    name: botong-zuul
  rabbitmq:
      host: ${rabbitmq.server}
      port: ${rabbitmq.port}
      username: ${rabbitmq.username}
      password: ${rabbitmq.password}
  cloud:
    config:
      fail-fast: true
      discovery:
        enabled: true
        service-id: botong-config
      profile: dev
      label: master

##配置路由忽略服务和是否重试；并利配置链接超时时间
zuul:
  ignoredServices: '*'
  retryable: true
  host:
      connect-timeout-millis: 30000
      socket-timeout-millis: 60000
  routes:
    admin:
      path: /admin/**
      serviceId: botong-admin
    microapps:
      path: /microapps/**
      serviceId: botong-micro-apps
    appcenter:
      path: /app-center/**
      serviceId: botong-app-center
    passport:
      path: /passport/**
      serviceId: botong-passport-domain
    org:
      path: /org/**
      serviceId: botong-org-structure
    im:
      path: /im/**
      serviceId: botong-im
  prefix: /api

##配置注册中心
eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.server}:${eureka.port}/eureka/
  instance:
    preferIpAddress: true

hystrix:
  threadpool:
    default:
      ##并发执行的最大线程数，默认10
      coreSize: 1000
      ##BlockingQueue的最大队列数
      maxQueueSize: 1000
      ##即使maxQueueSize没有达到，达到queueSizeRejectionThreshold该值后，请求也会被拒绝
      queueSizeRejectionThreshold: 500
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 50000
          strategy: SEMAPHORE

# 写入文件日志
logging:
  file: ${user.dir}/logs/${spring.application.name}.log

gate:
  ignore:
    uri: /admin/api/adminUser/login,/api/passport/user/login-code,/api/passport/user/send-login-code,/api/passport/user/login-pwd
    startWith: /microapps,/static