### 设置服务端口和Tomcat编码格式
server:
  port: 8000
  tomcat:
    uri-encoding: UTF-8

### 设置服务名称
spring:
  application:
    name: botong-zuul
  rabbitmq:
      host: ${rabbitmq.server}
      port: ${rabbitmq.port}
      username: ${rabbitmq.username}
      password: ${rabbitmq.password}
  cloud:
    config:
      fail-fast: true
      discovery:
        enabled: true
        service-id: botong-config
      profile: dev
      label: master
  # Redis数据库索引（默认为0）
    redis:
      database: 3
    # Redis服务器地址
      host: ${redis.server:192.168.10.48}
    # Redis服务器连接端口
      port: ${redis.port:10350}
    # Redis服务器连接密码（默认为空）
      password:
      # 连接超时时间（毫秒）
      timeout: 0
    # 连接池最大连接数（使用负值表示没有限制）
      pool:
        max-active: 8
    # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
    # 连接池中的最大空闲连接
        max-idle: 8
    # 连接池中的最小空闲连接
        min-idle: 0
    ## 配置配置中心服务

##配置路由忽略服务和是否重试；并利配置链接超时时间
zuul:
  ignoredServices: '*'
  retryable: true
  host:
      connect-timeout-millis: 30000
      socket-timeout-millis: 60000
  routes:
    admin:
      path: /admin/**
      serviceId: botong-admin
    microapps:
      path: /microapps/**
      serviceId: botong-micro-apps
    appcenter:
      path: /app-center/**
      serviceId: botong-app-center
    passport:
      path: /passport/**
      serviceId: botong-passport-domain
    org:
      path: /org/**
      serviceId: botong-org-structure
    im:
      path: /im/**
      serviceId: botong-im
    dang:
      path: /dang/**
      serviceId: botong-dang
  prefix: /api
  #限流配置
  ratelimit:
      key-prefix: botong
      enabled: true
      repository: REDIS
      behind-proxy: true
      default-policy: #optional - will apply unless specific policy exists
          limit: 100 #optional - 每个刷新时间窗口对应的请求数量限制
          refresh-interval: 30 # 刷新时间窗口的时间，默认值 (秒)
          type:
           - user

##配置注册中心
eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.server}:${eureka.port}/eureka/
  instance:
    preferIpAddress: true

hystrix:
  threadpool:
    default:
      ##并发执行的最大线程数，默认10
      coreSize: 1000
      ##BlockingQueue的最大队列数
      maxQueueSize: 1000
      ##即使maxQueueSize没有达到，达到queueSizeRejectionThreshold该值后，请求也会被拒绝
      queueSizeRejectionThreshold: 500
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 50000
          strategy: SEMAPHORE

# 写入文件日志
logging:
  file: ${user.dir}/logs/${spring.application.name}.log

gate:
  ignore:
    uri: /admin/api/adminUser/login,/passport/user/login-code,/passport/user/send-login-code,/passport/user/login-pwd
    startWith: /microapps,/static