### 设置服务端口和Tomcat编码格式
server:
  port: 10100
  tomcat:
    uri-encoding: UTF-8

### 设置服务名称
spring:
  application:
    name: botong-eureka

eureka:
  ##微服务修改减短服务心跳的时间
  instance:
      lease-expiration-duration-in-seconds: 1
      lease-renewal-interval-in-seconds: 1
      preferIpAddress: true
  server:
    enable-self-preservation: false # 开启Eureka自我保护机制,(dev环境下，关闭自我保护，注册服务列表会自动剔除已关闭服务)
    eviction-interval-timer-in-ms: 1000 # 检查服务失效时间(测试环境，1秒检测）


  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:10100/eureka/

logging:
  file: ${user.dir}/logs/${spring.application.name}.log
  level: info















