### 设置服务端口和Tomcat编码格式
server:
  port: 10100
  tomcat:
    uri-encoding: UTF-8

### 设置服务名称
spring:
  application:
    name: botong-eureka

eureka:
  ##微服务修改减短服务心跳的时间
  instance:
      lease-expiration-duration-in-seconds: 10
      lease-renewal-interval-in-seconds: 3

  server:
    enable-self-preservation: false # 开启Eureka自我保护机制
    eviction-interval-timer-in-ms: 3000 # 检查服务失效时间

  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://127.0.0.1:10100/eureka/

logging:
  file: ${user.dir}/logs/${spring.application.name}.log
  level: info















