### 设置服务端口和Tomcat编码格式
server:
  port: 23170
  tomcat:
    uri-encoding: UTF-8
    max-threads: 128 # 最大worker线程
    min-spare-threads: 64 # 最小worker线程
  undertow:
    io-threads: 8 # IO线程数，默认为CPU核心数，最小为2
    worker-threads: 40 # 阻塞任务线程池，值设置取决于系统的负载，默认为io-threads * 8
    buffer-size: 512 # 每块buffer的空间大小
    buffers-per-region: 10 # 每个区分配的buffer数量
    direct-buffers: true # 是否分配的直接内存


### 设置服务名称
spring:
  application:
    name: botong-micro-apps

##配置注册中心
eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.server}:${eureka.port}/eureka/
  instance:
    preferIpAddress: true
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 1

##配置路由忽略服务和是否重试；并利配置链接超时时间
zuul:
  ignoredServices: '*'
  retryable: true
  SendErrorFilter:
    error:
      disable: true
  host:
      connect-timeout-millis: 30000
      socket-timeout-millis: 60000
      max-total-connections: 500 # 每个服务的http客户端连接池最大连接，默认值是200
      max-per-route-connections: 50 # 每个route可用的最大连接数，默认值是20
  routes:
    appcenter-domain:
      path: /appcenter/**
      serviceId: botong-app-center-domain
    botong-approval:
      path: /approval/**
      serviceId: botong-approval
    botong-info:
      path: /info/**
      serviceId: botong-info
    botong-log:
      path: /log/**
      serviceId: botong-log
    botong-notice:
      path: /notice/**
      serviceId: botong-notice
    botong-sign:
      path: /sign/**
      serviceId: botong-sign
  ribbon-isolation-strategy: THREAD # 可选：SEMAPHORE THREAD

hystrix:
  threadpool:
    default:
      ##并发执行的最大线程数，默认10
      coreSize: 1000
      ##BlockingQueue的最大队列数
      maxQueueSize: 1000
      ##即使maxQueueSize没有达到，达到queueSizeRejectionThreshold该值后，请求也会被拒绝
      queueSizeRejectionThreshold: 500
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 50000
          strategy: SEMAPHORE


logging:
  file: ${user.dir}/logs/${spring.application.name}.log
  level: info