### 设置服务端口和Tomcat编码格式
server:
  port: 23170
  tomcat:
    uri-encoding: UTF-8

### 设置服务名称
spring:
  application:
    name: botong-micro-apps

##配置注册中心
eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.server}:${eureka.port}/eureka/
  instance:
    preferIpAddress: true
    lease-renewal-interval-in-seconds: 1
    lease-expiration-duration-in-seconds: 1

##配置路由忽略服务和是否重试；并利配置链接超时时间
zuul:
  ignoredServices: '*'
  retryable: true
  host:
      connect-timeout-millis: 30000
      socket-timeout-millis: 60000
      max-total-connections: 500 # 每个服务的http客户端连接池最大连接，默认值是200
      max-per-route-connections: 50 # 每个route可用的最大连接数，默认值是20
  routes:
    appcenter-domain:
      path: /appcenter/**
      serviceId: botong-app-center-domain
    botong-approval:
      path: /approval/**
      serviceId: botong-approval
    botong-info:
      path: /info/**
      serviceId: botong-info
    botong-log:
      path: /log/**
      serviceId: botong-log
    botong-notice:
      path: /notice/**
      serviceId: botong-notice
    botong-sign:
      path: /sign/**
      serviceId: botong-sign