server:
  port: 10400

spring:
  application:
    name: botong-zipkin
  sleuth:
    enabled: true
    sampler:
      percentage : 1
  rabbitmq:
    host: ${rabbitmq.server:192.168.10.47}
    port: ${rabbitmq.port:10222}
    username: ${rabbitmq.username:yunjing216}
    password: ${rabbitmq.password:yunjing216}
  datasource:
    url: jdbc:mysql://192.168.10.46:10150/botong-zipkin?autoReconnect=true&useUnicode=true&characterEncoding:UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: YunJing168
    driver-class-name: com.mysql.jdbc.Driver
    autoReconnect: true
    useUnicode: true
    characterEncoding: utf8
    type: com.alibaba.druid.pool.DruidDataSource   #这里是配置druid连接池，以下都是druid的配置信息
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  cloud:
    config:
      fail-fast: true
      discovery:
        enabled: true
        service-id: botong-config
      profile: dev
      label: master


### 注册eureka
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://192.168.10.233:10100/eureka/


zipkin:
  storage:
    type: mysql

## zipkin数据存储到elasticsearch中的配置
#zipkin:
#  storage:
#    StorageComponent: elasticsearch
#    type: elasticsearch
#    elasticsearch:
#      cluster: elasticsearch-zipkin-cluster
#      hosts: 127.0.0.1:10010
#     #pipeline=
#      max-requests: 64
#      index: zipkin
#      index-shards: 5
#      index-replicas: 1


# 写入文件日志
logging:
  file: ${user.dir}/logs/${spring.application.name}.log