server:
  port: 10400

spring:
  application:
    name: botong-zipkin
  rabbitmq:
    host: ${rabbitmq.server:192.168.10.47}
    port: ${rabbitmq.port:10222}
    username: ${rabbitmq.username:yunjing216}
    password: ${rabbitmq.password:yunjing216}
  datasource:
    url: ${spring.datasource.mysql.url}
    username: ${spring.datasource.mysql.username}
    password: ${spring.datasource.mysql.password}
    driver-class-name: com.mysql.jdbc.Driver
    initialize: true
    continue-on-error: true
#  cloud:
#    config:
#      fail-fast: true
#      discovery:
#        enabled: true
#        service-id: botong-config
#      profile: dev
#      label: master


### 注册eureka
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${eureka.server}:${eureka.port}/eureka/


zipkin:
  storage:
    type: mysql

## zipkin数据存储到elasticsearch中的配置
#zipkin:
#  storage:
#    StorageComponent: elasticsearch
#    type: elasticsearch
#    elasticsearch:
#      cluster: elasticsearch-zipkin-cluster
#      hosts: 127.0.0.1:10010
#     #pipeline=
#      max-requests: 64
#      index: zipkin
#      index-shards: 5
#      index-replicas: 1


# 写入文件日志
logging:
  file: ${user.dir}/logs/${spring.application.name}.log